version: 2
jobs:
  build:
    # docker:
    # - image: ubuntu:xenial
    executorType: machine
    working_directory: ~/virtlet
    steps:
    - checkout
    # - setup_remote_docker

    - run:
        name: Ensure prerequisites
        command: |
          sudo apt-get -qq update
          sudo apt-get install -y libxml2-utils jq curl ca-certificates openssh-client rsync
          sudo service apparmor stop
          sudo service apparmor teardown
          sudo update-rc.d -f apparmor remove
          sudo apt-get remove -y apparmor

    # - run:
    #     name: Install Docker client
    #     command: |
    #       set -x
    #       VER="17.03.0-ce"
    #       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
    #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
    #       mv /tmp/docker/* /usr/bin

    - run:
        name: Build virtlet
        command: |
          build/cmd.sh build
          build/cmd.sh copy

    - run:
        name: Run tests
        command: |
          build/cmd.sh test

    - run:
        name: Build virtlet image
        command: |
          docker build -t mirantis/virtlet .

    - run:
        name: Start the demo
        command: |
          NONINTERACTIVE=1 NO_VM_CONSOLE=1 INJECT_LOCAL_IMAGE=1 BASE_LOCATION="$PWD" deploy/demo.sh

    - run:
        name: Run e2e tests
        command: |
          tests/e2e/e2e.sh
